name: Deploy Lambda (ViaCEP)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Criar ambiente virtual
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip

    - name: Instalar dependências
      run: |
        source venv/bin/activate
        pip install flake8 bandit pytest -r requirements.txt

    - name: Verificar qualidade do código
      run: |
        source venv/bin/activate
        flake8 . --exclude=venv --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Verificar segurança do código
      run: |
        source venv/bin/activate
        bandit -r . --exclude venv,tests

    - name: Executar testes
      run: |
        source venv/bin/activate
        pytest tests/

    - name: Configurar credenciais AWS
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Empacotar aplicação
      run: |
        mkdir package
        pip install -r requirements.txt -t package/
        cp lambda_function.py package/
        cd package
        zip -r9 ../lambda_function.zip .

    - name: Fazer deploy na AWS Lambda
      run: |
        aws lambda update-function-code \
          --function-name api_viacep \
          --zip-file fileb://lambda_function.zip \
          --publish
