name: Deploy Lambda (ViaCEP) # Nome do workflow

on:
  push:
    branches:
      - main # O deploy será acionado quando houver um push na branch main

jobs:
  deploy:
    runs-on: ubuntu-latest # Em qual máquina virtual o job será executado

    steps:
    # Checkout do código
    - name: Checkout código 
      uses: actions/checkout@v3

    # Verificação de qualidade do código com flake8
    - name: Verificar qualidade do código
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

    # Configuração das credenciais AWS
    - name: Configurar credenciais AWS
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Instalar dependências e empacotar
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt -t .
        zip -r9 lambda_function.zip .

    - name: Fazer deploy na AWS Lambda
      run: |
        aws lambda update-function-code \
          --function-name api_viacep \
          --zip-file fileb://lambda_function.zip
